## ANTISPAM 1.5 (Firestar,Syamn)
# Main Configuration Settings
##

## maxChatMessages:
#     This is how many times a player can send messages to chat
##  Default: 5
maxChatMessages: 5

## maxMessageTime:
#     This is the amount of time they can send maxChatMessages to trigger the action
##  Default: 3
maxMessageTime: 3

## maxCommands:
#     This is the number of commands can be sent
##  Default: 5
maxCommands: 5

## maxCommandTime:
#     This is the amount of time they can send maxCommands to trigger the action
##  Default: 3
maxCommandTime: 3

## ignoreCommands:
#     This is the command prefix of ignore sent count
##  Default: /spawn, /home
ignoreCommands:
- /spawn
- /home

## tempBanDuration:
#        Only enabled when "actionTake: 5"
#     This is the time they are banned by the Measure (measure is the measurement of time)
##  Default: "5"
tempBanDuration: "5"

## tempBanDuration:
#        Only enabled when "actionTake: 5"
#     Measure is the measurement of time (m = minutes,h = hours,d = days)
##  Default: "m"
tempBanMeasure: "m"

## actionTake:
#     Actions you can make (1 = kick, 2 = bukkit ban, 3 = local ban, 4 = global ban, 5 = temporary ban)
##  Default: 1
actionTake: 1

#
## Customization Of Messages (Language)
#
tempBanMessage: "Spamming Bad :(, Temp Banned!"
localBanMessage: "Spamming Bad :(, Banned!"
kickMessage: "Spamming Bad :(, Kicked!"