name: antiSpam
main: com.firestar.antiSpam.main
version: 1.4
description: Stops spam in chat and command spam.
author: Firestar
commands:
permissions:
  antiSpam:
    description: Ignore chat from this player
    default: op