name: antispam
main: com.firestar.antiSpam.main
version: 1.5
description: Stops spam in chat and command spam.
author: Firestar,Syamn
permissions:
  antispam.ignore:
    description: Ignore chat from this player
    default: op